### ISSUE TITLE
cvc-id.3 in Eclipse WTP web-app_3_0

### ISSUE THREAD

**Issue by dougbreaux** [eclipse/lemminx#1137]
I opened [a bug against Eclipse](https://bugs.eclipse.org/bugs/show_bug.cgi?id=577715) and was pointed over here as the likely root cause.

web-app_3_0.xsd web.xml files have recently started giving many errors of the form:

```
cvc-id.3: A field of identity constraint ... matched element 'web-app', but this element does not have a simple type.
```

For example:
```
cvc-id.3: A field of identity constraint 'web-common-filter-name-uniqueness' matched element 'web-app', but this element does not have a simple type.
```

See details in https://stackoverflow.com/a/69091669/796761

Maybe started in Eclipse 2021-06

**Comment by angelozerr** [comment]
This problem comes from WWD Eclipse IDE, I think https://github.com/eclipse/wildwebdeveloper/issues/778 should fix this issue.

Please wait for new release of WWD and if problem occurs again please reopen this issue.

**Comment by dougbreaux** [comment]
It's unclear to me the progression, but I just know that this problem still exists with the latest Eclipse update. Is it that this is closed because https://github.com/eclipse/wildwebdeveloper/issues/778 was opened, which was closed because https://github.com/eclipse/lemminx/issues/1182 was opened? Which is not yet addressed?

**Comment by angelozerr** [comment]
Which release of wwd have you installed? Have you installed wtp?

**Comment by dougbreaux** [comment]
"Eclipse IDE for Enterprise Java and Web Developers (includes Incubating components)" version 2022-03

Which I think includes WTP? What I see if I filter by "wtp" is some m2e stuff and this:
```
  Web Development Tools	21.0.900.v20210916_2134	com.ibm.wdt.webtools.top.feature.feature.group	IBM
    Java EE Development Tools	1.0.401.v20210916_2134	com.ibm.wdt.javaee.feature.feature.group	IBM
      WTP Extensions	1.0.200.v20210916_2134	com.ibm.etools.wtp.extensions.feature.feature.group	IBM
```

**Comment by angelozerr** [comment]
@mickaelistria have you some idea?

**Comment by diabolusss** [comment]
Hello! Recently i've got the same problem just after eclipse modules upgrade (and system upgrade). Before upgrade, no errors were reported there.

**Comment by mickaelistria** [comment]
Can you please try to look at the running `java` process and share the whole command line of the process that contains "lemminx" in the command?

**Comment by angelozerr** [comment]
They were indeed a problem with lemminx XML catalog, which didn't load correctly the WTP XML editor. The issue should be fixed with https://github.com/eclipse/lemminx/issues/1199 (please wait a release of lemminx and WWD).

> Nothing with "wwd"

@[dougbreaux](https://github.com/dougbreaux) I think you should try to search with Wild Web Developer.:

![image](https://user-images.githubusercontent.com/1932211/171173651-13e723e7-7929-4f3b-897d-4bd6cf89943a.png)

**Comment by diabolusss** [comment]
> Can you please try to look at the running `java` process and share the whole command line of the process that contains "lemminx" in the command?

Sorry, i don't have such process. But i have WWD installed and my version matches with @angelozerr provided screenshot.

**Comment by dougbreaux** [comment]
@angelozerr 

Nothing "Wild" at all.

![image](https://user-images.githubusercontent.com/25640850/171191390-b3b79c20-592d-414a-ab1b-ba8fa7080982.png)

**Comment by angelozerr** [comment]
@dougbreaux what about plugin tab?

![image](https://user-images.githubusercontent.com/1932211/171209220-4901e307-7338-466b-8a0d-3478311a65d6.png)

**Comment by dougbreaux** [comment]
Ahh, there we go:
![image](https://user-images.githubusercontent.com/25640850/171218768-5e07b6f3-4274-41d4-815a-0a76233b4b2a.png)

**Comment by dougbreaux** [comment]
Picked up some more updates, slight version change on XML support, but same problem:
![image](https://user-images.githubusercontent.com/25640850/173929480-c9442065-c873-4b6b-80b6-944123e782e9.png)

**Comment by patric-r** [comment]
Why is this issue closed? It still appears and therefore should be reopened.
Is there a workaround available?

**Comment by angelozerr** [comment]
It is closed because LemMinX 0.21.0 should fix the problem now. But it requires that WWD embeds this lemminx version.

@mickaelistria is there à WWD release which embeds lemminx 0.21 version?
