### ISSUE TITLE
Invalid "schemaLocation" is not reported

### ISSUE THREAD

**Issue by WolfgangHG** [eclipse/lemminx#1143]
I first created [https://bugs.eclipse.org/bugs/show_bug.cgi?id=578009](https://bugs.eclipse.org/bugs/show_bug.cgi?id=578009) and was pointed here:

The new LanguageServer based validation in Eclipse does not report errors when a xml file has an invalid schemaLocation.

This is a valid XML file:
```
<application xmlns="https://jakarta.ee/xml/ns/jakartaee"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="https://jakarta.ee/xml/ns/jakartaee https://jakarta.ee/xml/ns/jakartaee/application_9.xsd">
	
	<invalid>
	</invalid>
</application>
```
Two errors are reported in this file (missing attribute "version" on root element, the child element "invalid" is invalid).

Now, change anything in the schemaLocation URI to make it invalid:
```
<application xmlns="https://jakarta.ee/xml/ns/jakartaee"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="https://jakarta.ee/xml/ns/jakartaee https://jakarta.ee/xml/ns/jakartaee/application_9.xsdaaaaaaaa">
	
	<invalid>
	</invalid>
</application>
```

Here, no error at all is shown for this file.

I would expect a message "schema location xyz could not be resolved" or similar.

**Comment by WolfgangHG** [comment]
The issue also arises for local paths, so that it is not a matter of the 404 error when requesting the XSD:

```
<?xml version="1.0" encoding="UTF-8"?>
<application xmlns="https://jakarta.ee/xml/ns/jakartaee"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="https://jakarta.ee/xml/ns/jakartaee file:///C:/Temp/wildfly-26.0.0.Final/docs/schema/application_9.xsdaaa">
	<invalid>
	</invalid>
</application>
```

**Comment by angelozerr** [comment]
It should report an error but with warning severity.

**Comment by angelozerr** [comment]
@WolfgangHG you are right, there were a bug. I have fixed in https://github.com/eclipse/lemminx/pull/1155 I refactor a lot of thing with the download process and now it should work:

![image](https://user-images.githubusercontent.com/1932211/151799228-0510dfda-e97f-4bca-8b57-f2a1d08ce1df.png)

We plan to do a release soon, after that WWD will adopt it.

//cc @mickaelistria

**Comment by WolfgangHG** [comment]
I don't see this warning when using Eclipse 2022-6, the original problem is still present. Is the fix contained in this version?

**Comment by angelozerr** [comment]
Which version of WWD are you using?

**Comment by angelozerr** [comment]
I suggest that you install last version of WWD https://github.com/eclipse/wildwebdeveloper/releases/tag/0.15.0

**Comment by WolfgangHG** [comment]
I downloaded the windows version from [https://download.eclipse.org/wildwebdeveloper/releases/latest/IDEs/](https://download.eclipse.org/wildwebdeveloper/releases/latest/IDEs/), but also here this issue still happens. 
I am not sure about the version numbers, but the plugin "Eclipse Wild Web Developer project - XML support using Language Server" has version 0.15.0.202207081036.
I assume LemMinx 0.18.3 or newer is required? How can I check this version?

**Comment by angelozerr** [comment]
Ok let me rsome time to retry again with WWD 0.15 to see what it happens.

**Comment by angelozerr** [comment]
> How can I check this version?

I fear it is not possible. with UI, but you can know that if you open the git.properties  from the given JAR:

![image](https://user-images.githubusercontent.com/1932211/184045129-f739fbc0-d922-4f4b-a0cf-dc816665076e.png)

You should see in this file:

`git.build.version=0.21.0
`

**Comment by angelozerr** [comment]
You need to set `Enable schema based validation` to `Always `:

![image](https://user-images.githubusercontent.com/1932211/184047144-7b3d34e6-54e2-4b4d-84ef-066440d7db8c.png)

After that you should see:

![image](https://user-images.githubusercontent.com/1932211/184047274-c5416748-3625-4ab7-8c74-e75ecf6125a7.png)

@mickaelistria @vrubezhny  is there any reason that `Enable schema based validation` is not set by default to `Always`? In vscode-xml we have that.

**Comment by WolfgangHG** [comment]
But shouldn't a warning be reported **always** if a schemaLocation is defined and the file cannot be resolved, in in mode "In valid schema"? This would probably be a "bug" in the declaration?

What does the setting "Always" mean?  I see that an error about an undefined "jboss-web" element is reported in my sample. This error does not come if the schemaLocation is removed and the xml file is schemaless. So it tries to validate files where it cannot resolve the XSD or the XSD contains errors?


By the way (sorry, might be a new issue - I can create another one if you consider it a bug): when switching to "Always", the "system-catalog.xml" file that was generated from the "JBoss Tools" plugin entries, shows validation errors for DTD files:
![catalogvalidation](https://user-images.githubusercontent.com/138049/184218733-e618daf7-cf57-4efe-a042-853cf1a99a1c.png)

`cvc-pattern-valid: Value '-//Sun Microsystems, Inc.//DTD J2EE Application 1.3//EN' is not facet-valid with respect to pattern '[a-zA-Z0-9\-'\(\)+,./:=?;!*#@$_%]*' for type 'publicIdentifier'.`

It seems the space is missing in the RegEx?

**Comment by angelozerr** [comment]
> But shouldn't a warning be reported always if a schemaLocation is defined and the file cannot be resolved, in in mode "In valid schema"? This would probably be a "bug" in the declaration?

I suggest that you create an issue for that to discuss about that but I dont know if it is easy to implement your suggestion beczuse it is the behavior of xerces.

> What does the setting "Always" mean? I see that an error about an undefined "jboss-web" element is reported in my sample. This error does not come if the schemaLocation is removed and the xml file is schemaless. So it tries to validate files where it cannot resolve the XSD or the XSD contains errors?

If you remove shemaLocation your xml is not validated by a xsd, (except if the xml defined à namespace which matche a catalog entry).and you have only syntax error. Always is just when you define a schemaLocation.

> By the way (sorry, might be a new issue - I can create another one if you consider it a bug): 

Please create an issue but it seems the problem comes from the xsd or dtd catalog.

**Comment by WolfgangHG** [comment]
New issue #1272 created for the schemaLocation validation and eclipse/wildwebdeveloper#847 for catalog validation (don' know whether it is an lemminx or wildwebdeveloper issue).
